### PR TITLE
Add "volatile" to two fields of rtlsdr_dev

### PR DESCRIPTION
**Pull request by blacklion**
librtlsdr uses two fileds of struct rtlsdr_dev to communicate
between threads. On hardware with weak memory model it is not
guaranteed that it will work, as C memory model guarantees
nothing for simple variables.

 Using C11 atomics seems to be overkill here, but async_status
and async_cancel better be marked as "volatile".

### CODE REVIEW

**Comment by paulotorrens** [comment]
@racerxdl asked me to comment on this issue on his behalf.

[Volatile is not effective for multi-threaded](http://stackoverflow.com/questions/4557979/when-to-use-volatile-with-multi-threading) applications as one would expect (though [Visual Studio uses it that way](https://bartoszmilewski.com/2008/12/01/c-atomics-and-memory-ordering/), it's not portable!). This _might_ work, but out of chance. Using a mutex or the atomic primitives C provides would be the right way. (Note that C11 and C++11 memory models are meant to be compatible.)

And now he owns me a coke.

**Comment by blacklion** [comment]
I know about volatile "controversy". Problem is, before C11 there was no memory model and "volatile" was only way to have some (not formally defined!) guarantees. For example, it was only safe way to communicate between signal handler and main code in UNIX-like OSes.

Yes, it will be better to use C11 atomics, problem is MS' compiler refuses to support C11 (not C++11 and beyond!). Maybe, some conditional compilation?

P.S. I'm surprised that current code works on multicore ARMs. On x86 (32/64) it works, as Intel's memory model is very strict, there are no surprises for me.

P.P.S. "volatile" is used in RPC driver, though ;-)

**Comment by paulotorrens** [comment]
@blacklion, as I told @racerxdl on Facebook, "this is worth being accepted", since, as you said, better to have it volatile than having it plain as it is. Got my approval, but, sadly, this is a weak guarantee of correctness. Microsoft's commitment to C89 is sure a problem... 😞

Maybe some documentation should be added to state that, if anything fails, this would be a possible cause for future investigation.

**Comment by jpoirier** [comment]
I believe in C, accessing a volatile qualified type through a nonvolatile qualified type is undefined behavior?

**Comment by blacklion** [comment]
@jpoirier Ouch, yes, you are right. So, `async_cancel` can not be marked as `volatile`.

**Comment by jpoirier** [comment]
An anecdote - the [stratux project](https://github.com/cyoung/stratux) uses librtlsdr (in thousands of system) to run up to two sdr dongles concurrently and targets mainly ARM boards (RPi2/RPi3/etc, all with weak memory models) and there have been no related issues that I'm aware of, but maybe @cyoung can comment.

**Comment by blacklion** [comment]
@jpoirier It is possible, that something (for example, USB driver, and it is very good candidate - it communicate with hardware, DMA and such) uses full barriers inside and this provides consistency here.
Ok, maybe I'm too paranoid.

**Comment by jpoirier** [comment]
@blacklion I don't think you're being paranoid at all. My guess as to why it appears to work on hardware with a weak memory model is that on said hardware data dependency ordering is maintained?

**Comment by hayguen** [comment]
would suggest to accept these patches: for sure volatile is safer than nothing

**Comment by xloem** [comment]
recommend documentation be updated to specify that rtlsdr_cancel_async only be called from within the async callback function, as the proper solution would be to access these values with locking primitives or atomic constructs.  the multithreaded clients can provide locking.
note that current cancellation behavior doesn't interrupt usb events loop while timing out anyway, as that's not the function of the completion flag passed to libusb.  canceling only within callback should introduce no extra delays.

**Comment by hayguen** [comment]
as this is outstanding for long time .. i simply accept this PR.
if there are REAL problems with this, one can open a new issue.

**Pull request closed without merging**
