### PR TITLE
Development

### PR DESCRIPTION
**Pull request by hayguen**
Have a look at the rtl_fm option '-C' for the command file!

### CODE REVIEW

**Comment by racerxdl** [comment]
:+1: 

I didn't had time to take test, but features are looking good :D

**Comment by racerxdl** [comment]
I will do a quick test here to merge it.

**Review by racerxdl — APPROVED** [review]
Tested on Linux. Working fine.

Have you checked for Windows? If its ok on windows you can merge it :dancers:

**Comment by hayguen** [comment]
Yes, i tested it on Windows.
That were the examples with executing notepad and so. Unfortunately no cool commands like ssmtp on Linux for sending eMail ..

**Pull request merged**
