### PR TITLE
Development

### PR DESCRIPTION
**Pull request by janspeller**

### CODE REVIEW

**Comment by hayguen** [comment]
what is this about?
why closed - without awaiting any reaction?

**Comment by janspeller** [comment]
> what is this about? why closed - without awaiting any reaction?

I was merging some local branches and selected the wrong target repository, sorry

**Comment by hayguen** [comment]
out of curiosity: which repo is the "right" one?

**Comment by janspeller** [comment]
> out of curiosity: which repo is the "right" one?

My own fork, i fixed some use-case specific stuff, especially reconnecting the sdr stick if it was disconnected before or powered off

**Pull request closed without merging**
