### PR TITLE
Added option '-w' to rtl_sdr that allows setting the tuner bandwidth.

### PR DESCRIPTION
**Pull request by lmutt**
A simple commit that allows setting the tuner bandwidth in "rtl_sdr" command line utility.

### CODE REVIEW

**Comment by racerxdl** [comment]
I was almost sure that this was already there lol

**Comment by hayguen** [comment]
me too

**Comment by lmutt** [comment]
I double check the librtlsdr/src/rtl_sdr.c in master and development branch... both have been updated about 3 years ago and don´t have this option to select the tuner bandwidth.

**Comment by hayguen** [comment]
you are right. I added this option primarily for rtl_tcp and rtl_fm .. but forgot about rtl_sdr.

**Comment by racerxdl** [comment]
Btw @lmutt  this should be merged to Development, not master.

**Review by racerxdl — APPROVED** [review]

**Comment by lmutt** [comment]
Thank you!

**Pull request merged**
