### PR TITLE
Added Bias T Support from RTL-SDR Blog V3 Dongle

### PR DESCRIPTION
**Pull request by racerxdl**
I added Software Enabled Bias T support from V3 Dongle of RTLSDR Blog (see http://www.rtl-sdr.com/rtl-sdr-blog-v-3-dongles-user-guide/ )

I didn't got any V3 dongles yet (I ordered mine yesterday), I will test it when it arrives.

### CODE REVIEW

**Comment by jpoirier** [comment]
LGTM

**Comment by racerxdl** [comment]
I added a Fix to the GPIO as well. 

Thanks for the RTL-SDR Blog admin for telling me this ^^

http://www.rtl-sdr.com/new-rtl-sdr-blog-units-now-available-in-store-hf-via-direct-sampling-software-switchable-bias-tee-less-noisespurs/#comment-81366

**Comment by hayguen** [comment]
Great thing. We need to wait delivery for testing ...  :-(

**Comment by hayguen** [comment]
received the rtl-sdr v3 dongle :-)
added command line option '-E biasT' to rtl_fm,
measured the voltage with a multimeter with and without that option:
4.5 volt when using the option.
so, it does the right thing.

**Comment by racerxdl** [comment]
Nice! So we can merge it ^^

**Pull request merged**
