### PR TITLE
Specify number of seconds to run

### PR DESCRIPTION
**Pull request by psa-jforestier**
Add a "-R nnn" option to run rtl_fm for a specific number of second, and cleanly exit after this time. Inspired by a similar option "-T" in https://github.com/merbanan/rtl_433

### CODE REVIEW

**Comment by hayguen** [comment]
all changes/patches should be prepared for the development branch.

**Comment by racerxdl** [comment]
@hayguen changed to development. Looks like it `compiles`. Need to be tested.

**Comment by psa-jforestier** [comment]
Maybe I missed the information, but you should indicate somewhere on the project (wiki pages or a readme file) how to contribute, and on which branch we should pull request.

**Comment by hayguen** [comment]
did minimal testing.
does run as expected.

**Comment by hayguen** [comment]
resolved minor conflicts and commited/pushed onto development

**Pull request closed without merging**
